#ifndef _CLI_H
#define _CLI_H

#define CLI_POINTER ">"
#define CLI_CONTINUE 1
#define CLI_TERMINATE 0
#define CLI_QUESTION "?"
#define CLI_NEW_LINE '\n'
#define CLI_STRING_TERMINATOR '\0'
#define CLI_READ_LINE_BUFFER_SIZE 1024
#define CLI_SPLIT_LINE_BUFFER_SIZE 64
#define CLI_SPLIT_LINE_TOKEN_DELIMITER " \t\r\n\a"
#define CLI_CHARACTER_EXIT 3
#define CLI_CHARACTER_TAB 9
#define CLI_CHARACTER_MINUS 45
#define CLI_CHARACTER_CARRIAGE_RETURN 13
#define CLI_CHARACTER_SPACE 32
#define CLI_CHARACTER_ARROW 91
#define CLI_CHARACTER_QUESTION_MARK 63
#define CLI_CHARACTER_UP_ARROW 65
#define CLI_CHARACTER_DOWN_ARROW 66
#define CLI_CHARACTER_DELETE 127

/**
 * CLI Start Point
 */
void cli_start(void);

#endif
